version: '2'

services:
    
    notebook:
        container_name: python
        build: ./python
        volumes:
            - ./src:/src
        networks:
            - bigdata_net
        tty: true

    mongo:
        container_name: mongo
        image: mongo:latest
        ports:
            - 27017:27017
        networks:
            - bigdata_net
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=12345
            - MONGO_INITDB_DATABASE=mongo_db
        volumes:
            - /var/lib/mongodb
            - ./src:/src

    redis:
        container_name: redis  
        image: redis:latest
        networks:
                - bigdata_net
        volumes:
            - ./src:/src

    cassandra:
        container_name: cassandra
        image: cassandra:latest
        ports:
            - "9042:9042"
        environment:
            - "MAX_HEAP_SIZE=256M"
            - "HEAP_NEWSIZE=128M"
        restart: always
        networks:
            - bigdata_net
        volumes:
            - /var/lib/cassandra
            - ./src:/src

    neo4j:
        container_name: neo4j
        image: neo4j:latest
        ports:
            - "7474:7474"
            - "7687:7687"
        environment:
            - NEO4J_AUTH=neo4j/12345
            - NEO4J_HEAP_MEMORY=2048
            - NEO4J_CACHE_MEMORY=1G
            - NEO4J_dbms_security_procedures_unrestricted=apoc.*
            - NEO4J_apoc_import_file_enabled=true
            - NEO4J_dbms_shell_enabled=true
        networks:
            - bigdata_net
        volumes:
            - ./src:/src

networks:
  bigdata_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.19.210.0/24
        gateway: 172.19.210.1
      
